### ISSUE TITLE
PATCH fails with 500

### ISSUE THREAD

**Issue by M-J-Brown** [jchapuis/leases4s#40] opened 2024-10-23 15:04 UTC
Hello 👋  great library, which I'd love to use, but I'm having a bit of trouble.

I'm getting lots of errors:
`Failed to create lease fund-movements for ed436b8e-7850-4877-a732-f90e5e026519: Internal Server Error`

I eventually managed to track down, in the kubernetes service api logs:
```
    "requestURI": "/apis/coordination.k8s.io/v1/namespaces/test/leases/fund-movements",
    "verb": "patch",
```
...
```
    "responseStatus": {
        "metadata": {},
        "status": "Failure",
        "message": "strconv.ParseUint: parsing \"nil\": invalid syntax",
        "code": 500
    },
```

As the only place the string "nil" appears in the library is in [Version.scala](https://github.com/jchapuis/leases4s/blob/07203514ae68ab656c2c571908cbfa8c9d61a963/core/src/main/scala/io/github/jchapuis/leases4s/impl/model/Version.scala#L5):
`  val Nil: Version = Version("nil")`

Looks to me like something in kubernetes is assuming that the lease version is a number, possibly in order to increment it?

I am on an old K8s version (1.26), which might be the issue.
Would a default of `val Nil: Version = Version("0")` perhaps be more compatible?

I can't find any documentation on HOW these versions get incremented!

**Comment by jchapuis** [comment] 2024-10-23 18:12
Thanks, good catch!

Yeah so the `resourceVersion` field is supposed to be opaque and just returned by the client. However, I noticed that in the our particular use case it was needed for object creation to avoid overriding the existing one. I don't know whether this was a design oversight from k8s. 

According to [docs](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency), even though it mentions that no assumptions should be made about the type, they currently use a value from ETCD which is `int64 mod_revision = 3;` so it's an int.

This might vary per kube distribution also, I can't reproduce it with k3d. But I think that anyway zero is a safer bet. Opening a PR now, will release asap.

**Comment by jchapuis** [comment] 2024-10-24 08:02
released in `0.3.0` let me know if it works

**Comment by M-J-Brown** [comment] 2024-10-24 09:52
`0.3.0` has changed to a different error:

`"Failed to create lease fund-movements for 517f6bfa-4b9e-48d8-a4ff-2baff2f91849: Unprocessable Entity"`
and corresponding api logs:
```
"responseStatus": {
        "metadata": {},
        "status": "Failure",
        "message": "leases.coordination.k8s.io \"test-lease\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update",
        "reason": "Invalid",
        "details": {
            "name": "test-lease",
            "group": "coordination.k8s.io",
            "kind": "leases",
            "causes": [
                {
                    "reason": "FieldValueInvalid",
                    "message": "Invalid value: 0x0: must be specified for an update",
                    "field": "metadata.resourceVersion"
                }
            ]
        },
        "code": 422
    }
```

I'm on AWS EKS if that counts for anything.

LMK if you'd rather I open a new issue!

**Comment by jchapuis** [comment] 2024-10-24 10:32
ok, reopening, let me dig further then

**Comment by jchapuis** [comment] 2024-10-24 18:19
@M-J-Brown let me know if `0.3.1` solves the problem

**Comment by M-J-Brown** [comment] 2024-10-25 09:43
That seems to be working! 🥳 thanks for the fast responses.

Just for my own understanding, following #43, there's now actually no explicit version tracking at all? The library just relies on the create succeeding to know that no-one else has created the same lease?

**Comment by jchapuis** [comment] 2024-10-26 15:09
> The library just relies on the create succeeding

Yes, that's built-in, Kube will return a 409 when trying to create a resource with the same name in the same namespace. Previously I was just using the wrong helper, where failure lead to using PATCH so I had to provide a version to make it fail, if that makes sense.

**Closed by jchapuis** 2024-10-26 15:09 UTC
